version: 2.1

orbs:
  node: circleci/node@4.1.0

jobs:
  test:
    executor:
      name: node/default
      tag: "14.15.4"
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm test
      - store_test_results:
          path: test-results/mocha
      - store_artifacts:
          path: test-results/newman/newman-results.html

workflows:
  newman-and-monitor:
    jobs:
      - test
